apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::887749253250:role/eksctl-testingcluster-nodegroup-t-NodeInstanceRole-W8RK336K47PN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::887749253250:role/codebuild-democicdbuild-service-role
      username: codebuild-democicdbuild-service-role
    - groups:
      - system:masters
      rolearn: arn:aws:iam::887749253250:role/codebuild-democicdbuild-service-role
      username: codebuild-democicdbuild-service-role
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-15T13:08:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "274952"
  uid: da2c2722-e945-415d-a7d1-0d3f7c7f3d98
